# ============================================================================
# PostgreSQL Database - Shared by Open WebUI and Perplexica
# ============================================================================

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: carian-data
  labels:
    app: postgresql
    component: database
data:
  POSTGRES_DB: cariandb
  PGDATA: /var/lib/postgresql/data/pgdata

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: carian-data
  labels:
    app: postgresql
    component: database
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        component: database
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsNonRoot: true
      
      containers:
        - name: postgresql
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          
          envFrom:
            - configMapRef:
                name: postgresql-config
          
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password
          
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
        
        # PostgreSQL Exporter for Prometheus metrics
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.15.0
          imagePullPolicy: IfNotPresent
          
          ports:
            - name: metrics
              containerPort: 9187
              protocol: TCP
          
          env:
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: username
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password
            - name: DATA_SOURCE_URI
              value: "localhost:5432/cariandb?sslmode=disable"
          
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
  
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
        labels:
          app: postgresql
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp3-retain
        resources:
          requests:
            storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: carian-data
  labels:
    app: postgresql
    component: database
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
    - name: metrics
      port: 9187
      targetPort: 9187
      protocol: TCP
  selector:
    app: postgresql

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-client
  namespace: carian-data
  labels:
    app: postgresql
    component: database
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql
