---
# ServiceMonitor for Open WebUI
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open-webui
  namespace: carian-apps
  labels:
    app: open-webui
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: open-webui
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - carian-apps

---
# ServiceMonitor for Perplexica
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: perplexica
  namespace: carian-apps
  labels:
    app: perplexica
    component: frontend
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: perplexica
      component: frontend
  endpoints:
    - port: http
      path: /api/metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - carian-apps

---
# ServiceMonitor for SearXNG
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: searxng
  namespace: carian-apps
  labels:
    app: perplexica
    component: searxng
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: perplexica
      component: searxng
  endpoints:
    - port: http
      path: /stats
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - carian-apps

---
# ServiceMonitor for PostgreSQL
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql
  namespace: carian-data
  labels:
    app: postgresql
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: postgresql
      component: metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - carian-data

---
# PrometheusRule for application alerts
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: carian-apps-alerts
  namespace: carian-apps
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: carian-apps
      interval: 30s
      rules:
        # Open WebUI alerts
        - alert: OpenWebUIDown
          expr: up{job="open-webui"} == 0
          for: 5m
          labels:
            severity: critical
            service: open-webui
          annotations:
            summary: "Open WebUI is down"
            description: "Open WebUI has been down for more than 5 minutes"
        
        - alert: OpenWebUIHighMemory
          expr: container_memory_usage_bytes{pod=~"open-webui.*"} / container_spec_memory_limit_bytes{pod=~"open-webui.*"} > 0.9
          for: 5m
          labels:
            severity: warning
            service: open-webui
          annotations:
            summary: "Open WebUI high memory usage"
            description: "Open WebUI memory usage is above 90%"
        
        - alert: OpenWebUIHighCPU
          expr: rate(container_cpu_usage_seconds_total{pod=~"open-webui.*"}[5m]) > 0.9
          for: 10m
          labels:
            severity: warning
            service: open-webui
          annotations:
            summary: "Open WebUI high CPU usage"
            description: "Open WebUI CPU usage is above 90%"
        
        # Perplexica alerts
        - alert: PerplexicaDown
          expr: up{job="perplexica"} == 0
          for: 5m
          labels:
            severity: critical
            service: perplexica
          annotations:
            summary: "Perplexica is down"
            description: "Perplexica has been down for more than 5 minutes"
        
        - alert: SearXNGDown
          expr: up{job="searxng"} == 0
          for: 5m
          labels:
            severity: critical
            service: searxng
          annotations:
            summary: "SearXNG is down"
            description: "SearXNG search backend has been down for more than 5 minutes"
        
        # Database alerts
        - alert: PostgreSQLDown
          expr: up{job="postgresql"} == 0
          for: 2m
          labels:
            severity: critical
            service: postgresql
          annotations:
            summary: "PostgreSQL is down"
            description: "PostgreSQL has been down for more than 2 minutes"
        
        - alert: PostgreSQLHighConnections
          expr: sum(pg_stat_activity_count) by (datname) / sum(pg_settings_max_connections) by (datname) > 0.8
          for: 5m
          labels:
            severity: warning
            service: postgresql
          annotations:
            summary: "PostgreSQL high connection usage"
            description: "PostgreSQL connection usage is above 80%"
        
        - alert: PostgreSQLReplicationLag
          expr: pg_replication_lag > 30
          for: 5m
          labels:
            severity: warning
            service: postgresql
          annotations:
            summary: "PostgreSQL replication lag detected"
            description: "PostgreSQL replication lag is above 30 seconds"

---
# PrometheusRule for SLO tracking
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: carian-slos
  namespace: carian-apps
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: slo-availability
      interval: 1m
      rules:
        # 99.9% availability SLO (43.2 minutes downtime/month)
        - record: slo:availability:open_webui
          expr: |
            avg_over_time(up{job="open-webui"}[30d])
        
        - record: slo:availability:perplexica
          expr: |
            avg_over_time(up{job="perplexica"}[30d])
        
        # Error budget
        - record: slo:error_budget:open_webui
          expr: |
            1 - slo:availability:open_webui
        
        - alert: SLOErrorBudgetExhausted
          expr: slo:error_budget:open_webui > 0.001
          for: 1h
          labels:
            severity: warning
          annotations:
            summary: "SLO error budget exhausted"
            description: "Open WebUI availability has fallen below 99.9% SLO"
