---
# PersistentVolumeClaim for Open WebUI data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: carian-apps
  labels:
    app: open-webui
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi

---
# Deployment for Open WebUI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: carian-apps
  labels:
    app: open-webui
    component: frontend
  annotations:
    description: "AI chat interface supporting multiple LLM backends"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
        component: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: open-webui
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          imagePullPolicy: Always
          
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          
          env:
            # Database configuration
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: open-webui-secrets
                  key: database-url
            
            # OpenAI API configuration
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: open-webui-secrets
                  key: openai-api-key
            
            # Application configuration
            - name: WEBUI_NAME
              value: "Carian Constellation AI"
            
            - name: ENABLE_SIGNUP
              value: "false"
            
            - name: DEFAULT_MODELS
              value: "gpt-4o,gpt-4o-mini"
            
            - name: ENABLE_COMMUNITY_SHARING
              value: "false"
            
            # Performance tuning
            - name: WEBUI_SESSION_COOKIE_SAME_SITE
              value: "lax"
            
            - name: WEBUI_SESSION_COOKIE_SECURE
              value: "true"
            
            - name: LOG_LEVEL
              value: "INFO"
          
          volumeMounts:
            - name: data
              mountPath: /app/backend/data
          
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: open-webui-data

---
# ServiceAccount for Open WebUI
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui
  namespace: carian-apps
  labels:
    app: open-webui

---
# Service for Open WebUI
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: carian-apps
  labels:
    app: open-webui
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: open-webui

---
# HorizontalPodAutoscaler for Open WebUI
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: open-webui
  namespace: carian-apps
  labels:
    app: open-webui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open-webui
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
# PodDisruptionBudget for Open WebUI
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: open-webui
  namespace: carian-apps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: open-webui
